name: Zip Root Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zip_files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a ZIP file containing all files in the root directory
      - name: Create ZIP file
        run: |
          mv rof2 darkmode
          zip -r darkmode-rof2.zip darkmode
          mv darkmode rof2
          mv thj darkmode
          zip -r darkmode-thj.zip darkmode
          mv darkmode thj

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Darkmode Maps"
          files: |
            darkmode-rof2.zip
            darkmode-thj.zip
